Arquillian
==========

*_So you rule your code. Not the bugs._*

.Community Project

Arquillian is an open, innovative and extensible testing platform that enables developers to easily create automated integration, functional and acceptance tests for Java software.

Testing is still the biggest challenge for developers building on the Java enterprise platform. Arquillian solves this problem in a radical way that not only makes testing possible, it gives tests real value. It even enables developers to take on scenarios previously considered untestable or too expensive to test.

Picking up where unit tests leave off, Arquillian handles all the plumbing of container management, deployment and framework initialization so you can focus on the task at hand, writing your tests. Real tests. In short…

Arquillian works by moving the code under test to the runtime so the test doesn’t need to embed or mock the runtime itself. Arquillian eliminates this burden by handling all aspects of test execution, which include:

* Managing the lifecycle of one or more containers
* Packaging the test case, dependent classes and resources into ShrinkWrap archives
* Deploying the archives to the containers
* Enriching the test case by providing dependency injection and other declarative services
* Running the client and/or in-container tests
* Capturing the results and transporting them to the test runner for reporting

As soon as you begin integrating components inside a runtime, whether it be embedded or standalone, you need a service to manage that runtime. That's Arquillian's core concern. Arquillian puts the code to test inside the runtime and then delegates to extensions to help integrate components, invoke services, navigate web pages, measure performance characteristics, report code coverage and pass tests through the cloud, just to name a few.

Arquillian provides a component model for tests, one that matches the programming model used to develop the application.

The Arquillian project adheres to three core principles:

. Tests should be portable to any supported container
. Tests should be executable from both the IDE and the build tool
. The platform should extend or integrate existing test frameworks

By focusing on these principles, Arquillian makes integration and functional tests as simple to write and execute as unit tests.

Find out more at http://arquillian.org

*_No more mocks. No more container lifecycle and deployment hassles. Just real tests!_*
