# Site configuration
site.url=https://arquillian.org

# Theme configuration
site.page-layout=default

# Content configuration
site.collections.docs=true
site.collections.docs.layout=post
site.collections.docs.future=true

site.collections.posts=true
site.collections.posts.layout=post

# Development mode
%dev.quarkus.http.port=8082
quarkus.http.port=8082

# Template configuration
quarkus.qute.strict-rendering=false
quarkus.qute.property-not-found-strategy=output-original
quarkus.qute.remove-standalone-lines=false


# Made with Bob
