# Site configuration
%prod.site.url=https://arquillian.org

# Theme configuration
site.page-layout=default

# Content configuration
site.collections.docs=true
site.collections.docs.layout=post
site.collections.docs.future=true

site.collections.posts=true
site.collections.posts.layout=post

# Development mode
%dev.quarkus.http.port=8082
quarkus.http.port=8082
quarkus.http.root-path=/roq

# Template configuration
quarkus.qute.strict-rendering=true
quarkus.qute.property-not-found-strategy=output-original
quarkus.qute.remove-standalone-lines=true

# Logging
quarkus.log.level=DEBUG
quarkus.log.file.enable=true
quarkus.log.file.path=roq.log
quarkus.log.file.format=%d{dd HH:mm:ss} %-5p [%c] (%t) %s%e%n
quarkus.log.category."io.quarkiverse.roq".level=DEBUG
